version: '3.7'
services:
  config-server:
    image: config-server:v1.0.0
    ports: 
      - "8888:8888"
    restart: always
    networks:
      - springcloud
  servicio-eureka-server:
    image: servicio-eureka-server:v1.0.0
    ports: 
      - "8761:8761"
    restart: always
    networks: 
      - springcloud
  microservicios-mysql8:
    image: mysql:8
    ports: 
      - "3306:3306"
    restart: always
    networks: 
      - springcloud
    environment:
      MYSQL_DATABASE: db_springboot_cloud
      MYSQL_ROOT_PASSWORD: devuser2019
  servicio-productos:
    image: servicio-productos:v1.0.0
    restart: always
    networks: 
      - springcloud
    depends_on: 
      - config-server
      - servicio-eureka-server
      - microservicios-mysql8
  servicio-items:
    image: servicio-items:v1.0.0
    ports: 
      - "8002:8002"
      - "8005:8005"
      - "8007:8007"
    restart: always
    networks: 
      - springcloud
    depends_on: 
      - config-server
      - servicio-eureka-server
      - servicio-productos
  servicio-zuul-server:
    image: servicio-zuul-server:v1.0.0
    ports: 
      - "8090:8090"
    restart: always
    networks: 
      - springcloud
    depends_on: 
      - config-server
      - servicio-eureka-server
      - servicio-productos
      - servicio-items
networks:
  springcloud: